### ISSUE TITLE
View is being chipped off

### ISSUE THREAD

**Issue by itsaark** [tiagomnh/THCircularProgressView#11]
Hi, Thanks so much for doing this.

I'm facing an issue when I implement this class using auto-layout on interface builder. The top and bottom on the view are being chipped off. I have a height constraint of 160. When the view loads, I have set the progress view radius to 70. But still the progress circle is being chipped off at top and bottom.

**Comment by itsaark** [comment]
I solved this by setting the aspect ratio of the ProgressView to 1:1 ratio. Sorry for raising such futile issue.

**Comment by tiagomnh** [comment]
No problem! Glad you figured that out. :wink:
