### ISSUE TITLE
centerLabel.text not working

### ISSUE THREAD

**Issue by goelv** [tiagomnh/THCircularProgressView#5]
Hi,

I'm trying to set the text of the center label but it is not working. I am using:

```
self.prog.centerLabel.text = [NSString stringWithFormat:@"Hi"];
```

where self.prog is my THCircularProgressView object.

**Comment by tiagomnh** [comment]
Hi! 

It isn't working because the centerLabel is hidden by default. You should set its visibility with one of the following properties:

```
self.prog.centerLabelVisible = YES;
// or
self.proc.centerLable.hidden = NO;
```

I've updated the example in the README to include this. Thanks for pointing this out to me! ;)

**Comment by goelv** [comment]
Thanks its working for me now!
